# Generated by Django 4.1.5 on 2023-01-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(default=0, max_length=150, verbose_name='Временный столбец'),
        ),
    ]
